# Generated by Django 3.2.24 on 2024-03-17 21:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20240315_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='new_desc',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
