# Generated by Django 3.2.24 on 2024-03-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_new_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_desc',
        ),
    ]
